
# Agent settings
MIN_STEERING = -1.0
MAX_STEERING = 1.0
MIN_THROTTLE = 0.3
MAX_THROTTLE = 0.5
MAX_STEERING_DIFF = 0.15

#HyperParameter

N_COMMAND_HISTORY = 10
REWARD_CRASH = -10
CRASH_REWARD_WEIGHT = 5
THROTTLE_REWARD_WEIGHT = 0.1