
# Agent settings
MIN_STEERING = -1.0
MAX_STEERING = 1.0
MIN_THROTTLE = 0.4
MAX_THROTTLE = 0.7
MAX_STEERING_DIFF = 0.15

#HyperParameter

N_COMMAND_HISTORY = 10
REWARD_CRASH = -10
CRASH_REWARD_WEIGHT = 5
THROTTLE_REWARD_WEIGHT = 0.1